name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change 'main' if your default branch has a different name.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if needed for your project)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use the Node.js version your project needs.

      # Step 3: Install dependencies (if using npm or yarn)
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (if necessary)
      - name: Build project
        run: npm run build  # Replace with your build command, or remove if no build step is needed.

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src  # Replace './build' with the folder containing your deployable files.
